description: Verify the deployment of an ECS revision.
usage:
  version: 2.1
  orbs:
    aws-cli: circleci/aws-cli@4.0
    aws-ecs: circleci/aws-ecs@4.0
  jobs:
    verify-deployment:
      docker:
        - image: cimg/python:3.10
      steps:
        - aws-cli/setup:
            # This example uses CircleCI's OpenID Connect Token to generate temporary AWS keys
            role_arn: "arn:aws:iam::123456789012:role/OIDC_ARN"
            region: AWS_REGION
            profile_name: "OIDC-PROFILE"
            session_duration: "3600"
            role_session_name: "example-session-name"
        - run:
            name: Get last task definition
            command: >
              TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                  --task_definition ${MY_APP_PREFIX}-service \
                  --output text \
                  --query 'taskDefinition.taskDefinitionArn' \
                  --profile default
                  --region ${AWS_DEFAULT_REGION})
              echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
              $BASH_ENV
        - aws-ecs/verify_revision_is_deployed:
            family: '${MY_APP_PREFIX}-service'
            cluster: '${MY_APP_PREFIX}-cluster'
            task_definition_arn: '${TASK_DEFINITION_ARN}'
  workflows:
    test-workflow:
      jobs:
        - verify-deployment:
            context: [CircleCI_OIDC_Token]
